#!/bin/bash

echo -e "\033[1;31mATTENTION!\033[0m"
echo " "
echo -e "\033[1;33mthis password will be used to login to your server
\033[0m"
echo -e "\033[1;32menter the new password \033[1;32m
to continue...\033[1;31m\033[0m"
read  -p : pass
(echo $pass; echo $pass)|passwd 2>/dev/null
sleep 1s
echo -e "\033[1;31mpassword changed successfully!\033[0m"
sleep 5s
cd
clear

