#!/bin/bash
#-----TheMentalistSay------
fun_swap() {
    clear
		echo -e "\E[44;1;37m            manage virtual memory             \E[0m"
        echo ""
		echo -e "\033[1;31mswap is a swap area used to increase the amount of ram \in the system (recommended for machines with low ram memory).\033[0m"
        echo -e "\033[1;31mbefore activating, know the amount of storage your machine has, \nalways leave extra storage to avoid crashes.\033[0m"
        echo ""
		echo -e "\033[1;31m[\033[1;36m1\033[1;31m] \033[1;37m• \033[1;33menable swap / change swap value \033[0m"
		echo -e "\033[1;31m[\033[1;36m2\033[1;31m] \033[1;37m• \033[1;33mdisable swap\033[0m"
		echo -e "\033[1;31m[\033[1;36m0\033[1;31m] \033[1;37m• \033[1;33mback\033[0m"
		echo ""
		echo -ne "\033[1;32mwhat do you want to do \033[1;33m?\033[1;37m "
		read resposta
		if [[ "$resposta" = '1' ]]; then
            clear
			echo -e "\E[44;1;37m            virtual memory              \E[0m"
			echo ""
			echo -ne "\033[1;32mhow many gigs do you want to use \033[1;33m?\033[1;37m: "
			read gigas
            [[ -z "$gigas" ]] && {
					echo ""
					echo -e "\033[1;31mgigas invalidates!"
					sleep 2
					clear
					menu
				}
            echo ""
			echo -e "\033[1;32mstarting virtual memory \033[1;31m$gigas GB\033[1;33m"
			echo ""
            swapoff -a
            rm -rf /bin/ram.img > /dev/null 2>&1
            fallocate -l ${gigas}G /bin/ram.img > /dev/null 2>&1
            chmod 600 /bin/ram.img > /dev/null 2>&1
            mkswap /bin/ram.img > /dev/null 2>&1
            swapon /bin/ram.img > /dev/null 2>&1
            echo 50  > /proc/sys/vm/swappiness
            echo '/bin/ram.img none swap sw 0 0' | sudo tee -a /etc/fstab > /dev/null 2>&1
            echo ""
			echo -e "\033[1;32mvirtual memory activated successfully\033[1;33m"
            sleep 2
			fun_swap
        elif [[ "$resposta" = '2' ]]; then
            clear
			echo -e "\E[44;1;37m            turning off virtual memory              \E[0m"
            swapoff -a
            rm -rf /bin/ram.img > /dev/null 2>&1
            echo ""
			echo -e "\033[1;32mvirtual memory disabled successfully!\033[1;33m"
			sleep 2
			fun_swap
        elif [[ "$resposta" = '0' ]]; then
			echo ""
			echo -e "\033[1;31mreturnning...\033[0m"
			sleep 1
			menu
		else
			echo ""
			echo -e "\033[1;31minvalid option !\033[0m"
			sleep 1
			fun_swap
		fi 
}
fun_swap